n = int(input("N: "))
k = int(input("K: "))
a = pow(2,k)
b = (n/a)
c = (n-b)
print("A:")
print(a)
print("B:")
print(b)
print("C:")
print(c)
print("Eliminated: "+str(c))
print("Remaining: "+str(b))